//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospiPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Consultas = new HashSet<Consultas>();
        }
    
        public int CitaID { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public Nullable<int> MedicoID { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
        public string Consultorio { get; set; }
        public Nullable<int> NumeroCita { get; set; }
        public Nullable<int> Duracion { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas> Consultas { get; set; }
    }
}
