//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospiPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenesPacientes
    {
        public int ExamenPacienteID { get; set; }
        public Nullable<int> ExamenID { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public Nullable<int> ConsultaID { get; set; }
        public Nullable<System.DateTime> FechaRealizacion { get; set; }
        public string Resultados { get; set; }
        public string Notas { get; set; }
        public Nullable<int> MedicoID { get; set; }
        public string Laboratorio { get; set; }
        public string ArchivoResultados { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        public virtual Examenes Examenes { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
