//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospiPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HospiPlusDBEntities1 : DbContext
    {
        public HospiPlusDBEntities1()
            : base("name=HospiPlusDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
        public virtual DbSet<Examenes> Examenes { get; set; }
        public virtual DbSet<ExamenesPacientes> ExamenesPacientes { get; set; }
        public virtual DbSet<Medicamentos> Medicamentos { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<PacientesAudit> PacientesAudit { get; set; }
        public virtual DbSet<Recetas> Recetas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int EliminarMedicoCompleto(Nullable<int> medicoID)
        {
            var medicoIDParameter = medicoID.HasValue ?
                new ObjectParameter("MedicoID", medicoID) :
                new ObjectParameter("MedicoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarMedicoCompleto", medicoIDParameter);
        }
    
        public virtual int EliminarPacienteCompleto(Nullable<int> pacienteID)
        {
            var pacienteIDParameter = pacienteID.HasValue ?
                new ObjectParameter("PacienteID", pacienteID) :
                new ObjectParameter("PacienteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPacienteCompleto", pacienteIDParameter);
        }
    
        public virtual ObjectResult<ObtenerExpedientePaciente_Result> ObtenerExpedientePaciente(Nullable<int> pacienteID)
        {
            var pacienteIDParameter = pacienteID.HasValue ?
                new ObjectParameter("PacienteID", pacienteID) :
                new ObjectParameter("PacienteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerExpedientePaciente_Result>("ObtenerExpedientePaciente", pacienteIDParameter);
        }
    
        public virtual int RegistrarConsultaReceta(Nullable<int> pacienteID, Nullable<int> medicoID, Nullable<int> citaID, Nullable<System.DateTime> fechaHora, string diagnostico, string tratamiento, string notas, Nullable<decimal> peso, Nullable<decimal> altura, Nullable<int> medicamentoID, string dosis, string instrucciones, Nullable<System.DateTime> fechaEmision, Nullable<int> duracion, Nullable<int> cantidad)
        {
            var pacienteIDParameter = pacienteID.HasValue ?
                new ObjectParameter("PacienteID", pacienteID) :
                new ObjectParameter("PacienteID", typeof(int));
    
            var medicoIDParameter = medicoID.HasValue ?
                new ObjectParameter("MedicoID", medicoID) :
                new ObjectParameter("MedicoID", typeof(int));
    
            var citaIDParameter = citaID.HasValue ?
                new ObjectParameter("CitaID", citaID) :
                new ObjectParameter("CitaID", typeof(int));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var diagnosticoParameter = diagnostico != null ?
                new ObjectParameter("Diagnostico", diagnostico) :
                new ObjectParameter("Diagnostico", typeof(string));
    
            var tratamientoParameter = tratamiento != null ?
                new ObjectParameter("Tratamiento", tratamiento) :
                new ObjectParameter("Tratamiento", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(decimal));
    
            var alturaParameter = altura.HasValue ?
                new ObjectParameter("Altura", altura) :
                new ObjectParameter("Altura", typeof(decimal));
    
            var medicamentoIDParameter = medicamentoID.HasValue ?
                new ObjectParameter("MedicamentoID", medicamentoID) :
                new ObjectParameter("MedicamentoID", typeof(int));
    
            var dosisParameter = dosis != null ?
                new ObjectParameter("Dosis", dosis) :
                new ObjectParameter("Dosis", typeof(string));
    
            var instruccionesParameter = instrucciones != null ?
                new ObjectParameter("Instrucciones", instrucciones) :
                new ObjectParameter("Instrucciones", typeof(string));
    
            var fechaEmisionParameter = fechaEmision.HasValue ?
                new ObjectParameter("FechaEmision", fechaEmision) :
                new ObjectParameter("FechaEmision", typeof(System.DateTime));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("Duracion", duracion) :
                new ObjectParameter("Duracion", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarConsultaReceta", pacienteIDParameter, medicoIDParameter, citaIDParameter, fechaHoraParameter, diagnosticoParameter, tratamientoParameter, notasParameter, pesoParameter, alturaParameter, medicamentoIDParameter, dosisParameter, instruccionesParameter, fechaEmisionParameter, duracionParameter, cantidadParameter);
        }
    }
}
