//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospiPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientesAudit
    {
        public int AuditID { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public string NombreAnterior { get; set; }
        public string NombreNuevo { get; set; }
        public string ApellidoAnterior { get; set; }
        public string ApellidoNuevo { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string UsuarioCambio { get; set; }
    }
}
