//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospiPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int RecetaID { get; set; }
        public Nullable<int> ConsultaID { get; set; }
        public Nullable<int> PacienteID { get; set; }
        public Nullable<int> MedicoID { get; set; }
        public Nullable<int> MedicamentoID { get; set; }
        public string Dosis { get; set; }
        public string Instrucciones { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
